### ISSUE TITLE
AS Image scraper failing, can we switch to html?

### ISSUE THREAD

**Issue by 1upkd** [DataKind-BLR/covid19bharat_scrapers#61]
The image scraper for Assam is failing with the exception as shown below:

```
Traceback (most recent call last):
  File "scrapers.py", line 172, in <module>
    live_data = fetch_data(states_all[state_code])
  File "scrapers.py", line 125, in fetch_data
    return fn_map[st_obj['state_code'].lower()](st_obj)
  File "/home/kd/datakind-blr/scrapers/statewise_get_data.py", line 131, in as_get_data
    if int(linesArray[len(linesArray) - 1]) > 0:
ValueError: invalid literal for int() with base 10: ' 19 since the first patient was detected on 31st '
```
![image](https://user-images.githubusercontent.com/24380482/145163575-3772f70a-76dc-4f14-8970-91818a459256.png)

Also, one of the sources mentioned has HTML data: https://covid19.assam.gov.in/all-districts/. Can we use this for scraping instead of the image?

**Comment by kaizer1v** [comment]
Since the htmls aren't regularly updated, it's not reliable to wait until they update it. Thus, volunteering team is using images
